
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace WeChat
{

using System;
    using System.Collections.Generic;
    
public partial class iot_control_panel
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public iot_control_panel()
    {

        this.iot_hardware_scene = new HashSet<iot_hardware_scene>();

        this.iot_scene = new HashSet<iot_scene>();

    }


    public int ID { get; set; }

    public int GateWayID { get; set; }

    public int Position { get; set; }

    public string Uid { get; set; }

    public string Name { get; set; }

    public Nullable<int> KeyNumber { get; set; }

    public Nullable<int> ParentID { get; set; }

    public Nullable<System.DateTime> CreateTime { get; set; }

    public Nullable<System.DateTime> EditTime { get; set; }



    public virtual iot_gateway iot_gateway { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<iot_hardware_scene> iot_hardware_scene { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<iot_scene> iot_scene { get; set; }

}

}
