
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace WeChat
{

    using System;
    using System.Collections.Generic;

    public partial class iot_elebox
    {

        public int ID { get; set; }

        public int Position { get; set; }

        public int GateWayId { get; set; }

        public string Uid { get; set; }

        public string Name { get; set; }

        public Nullable<System.DateTime> CreateTime { get; set; }

        public Nullable<System.DateTime> EditTime { get; set; }

        public virtual iot_gateway iot_gateway { get; set; }
        public string MAC { get; internal set; }
    }

}
