
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace WeChat
{

using System;
    using System.Collections.Generic;
    
public partial class iot_blank_position
{

    public int ID { get; set; }

    public int Position { get; set; }

    public int Type { get; set; }

    public int GateWayID { get; set; }



    public virtual iot_gateway iot_gateway { get; set; }

}

}
