

//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace WeChat
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class brhein_iotEntities : DbContext
{
    public brhein_iotEntities()
        : base("name=brhein_iotEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<iot_blank_position> iot_blank_position { get; set; }

    public virtual DbSet<iot_control_panel> iot_control_panel { get; set; }

    public virtual DbSet<iot_elebox> iot_elebox { get; set; }

    public virtual DbSet<iot_gateway> iot_gateway { get; set; }

    public virtual DbSet<iot_hardware_scene> iot_hardware_scene { get; set; }

    public virtual DbSet<iot_scene> iot_scene { get; set; }

    public virtual DbSet<iot_scene_panel> iot_scene_panel { get; set; }

    public virtual DbSet<iot_user> iot_user { get; set; }

}

}

